#include<iostream.h>
#include<conio.h>
void main(){
long int enroll;
float cpp,java,oracle;
clrscr();
cout<<"Enter student Enrollment no:";
cin>>enroll;
cout<<"\nEnter marks obtant in c++:";
cin>>cpp;
cout<<"\nEnter marks obtant in java:";
cin>>java;
cout<<"\nEnter Marks obtant in oracal:";
cin>>oracle;
clrscr();
cout<<"\n\t\t=====Student result======";
cout<<"\n\t\tStudent Enrolllmant no::"<<enroll;
cout<<"\n\t\tMarkas Obtant in \"c++\"::"<<cpp;
cout<<"\n\t\tMarkes obtant in\"java\"::"<<java;
cout<<"\n\t\tMarkas obtant in\"oracle\"::"<<oracle;
cout<<"\n\t\t===========================";
getch();
}